server:
  port: 8081
spring: 
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
    name: wangqing
server:
  port: 8082
---
spring:
  profiles: test
  application:
    name: lixiaohong
server:
  port: 8082